config/routes.rb
Rails.application.routes.draw do
  # get 'tweets/index'
  root 'tweets#index'
  resources :tweets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  def new
    @tweet = Tweet.new
  end
  def create
    @tweet = Tweet.new(
        message: params[:tweet][:message],
        tdate: params[:tweet][:tdate])
    @tweet.save
    redirect_to root_path
  end
  def show
    @tweet = Tweet.find(params[:id])
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(
      message: params[:tweet][:message],
      tdate: params[:tweet][:tdate])
      redirect_to root_path
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet, url: {action: :update} do |f| %>
  <%= f.text_area :message %>
  <br>
  <br>
  <%= f.submit '更新' %>
<% end %>

app/views/tweets/index.html.erb
<% require 'date' %>

<div class="left">
 <h1>近畿大学</h1>
 <div class="a">
  @kinkidaigakuPR
 </div>
 <p>近畿大学のTwitter公式アカウントです。気象警報による休講情報や、お得なランチ情報など、大学に関する情報を発信します。マグロに関するツイート多め🐟学生のみなさんの相談に乗りますので、くだらないことも気軽に話しかけてください。履修に関するご質問は所属学部。入試に関するご相談は、入学センターへお問い合わせ下さい。</p>
 <div class="a"><p>大阪府東大阪市</p></div>
 <div class="a"><p>🔗instagraam.cpm/kinkidagakupr</p></div>
 <div class="a"><p>🗓2010年12月に登録</p></div>
 <p><%= link_to 'ツイート',new_tweet_path %></p>
</div> 
<div class="right">
 <div class="b">
  <p>ツイート　　ツイートと返信　　メディア</p>
 </div>
 <% @tweets.each do|tweet| %>
  <p>
   <div class="c">
    <%= image_tag 'IMG_1232.JPG', :width => '50px', :height => '50px' %>
   </div>
   <div class="d">
     <div class="a">
      @kinkidaigakuPR      
      <% tweet.tdate = tweet.created_at %>
      <% t1 = tweet.tdate %>
      <% t2 = Time.current %>
      <% if (t2-t1) <= 60 * 60 %>
       <%= ((t2-t1) / 60) .to_i.to_s %>分前
      <% elsif (t2-t1) <= 60 * 60 * 24 %>
       <%= ((t2-t1) / 3600) .to_i.to_s %>時間前
      <% else %>
       <%= (t2.to_date - t1.to_date).to_i.to_s %>日前
      <% end %>
     </div>
    <%= tweet.message %>
    <br>
    <div class="a">
     <%= link_to '表示',tweet_path(tweet.id) %>
     <%= link_to '編集', edit_tweet_path(tweet.id) %>
     <%= link_to '削除', tweet_path(tweet.id), method: :delete %>
    </div>
   </div>
  </p>
 <% end %>
</div>

app/views/tweets/new.html.erb
<%= form_for @tweet do |f| %>
  <%= f.text_area :message %>
  <br>
  <br>
  <%= f.submit 'ツイートする'%>
<% end %>

app/views/tweets/show.html.erb
<%= @tweet.message %>
<br>
<br>
<%= link_to '戻る',root_path %>